import type { Metadata } from "next";
import "./globals.css";
import PageHeader from "@/templates/PageLayout/PageHeader/PageHeader";
import PageFooter from "@/templates/PageLayout/PageFooter/PageFooter";
import AppDropdown from "@/components/AppDropdown/AppDropdown";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <PageHeader />
            {children}
            <PageFooter />
         </body>
      </html>
   );
}
